### ISSUE TITLE
Validation error when attempting to create instance of model

### ISSUE THREAD

**Issue by ashamnx** [xiara-io/xiara-mongo#1]
First of all i must say love the whole project both mongo and web package especially since Im an angular developer <3. thank you for the awesome work.

**Error Details**
When i attempted to create a user with the model with the same code as in the Readme for userModel, but with another unique field for email. Im getting a error from validator.

`TypeError: Cannot read property 'constructor' of undefined
    at Function.SchemaValidator.validateField (/Users/ashamnx/Code/xiara-mongo/build/Definitions/Schema/SchemaValidator.js:15:18)
    at MongoSchema.validate (/Users/ashamnx/Code/xiara-mongo/build/Definitions/MongoSchema.js:101:50)
    at User.MongoCollection.insert (/Users/ashamnx/Code/xiara-mongo/build/Definitions/MongoCollection.js:210:39)
    at User.MongoCollection.save (/Users/ashamnx/Code/xiara-mongo/build/Definitions/MongoCollection.js:198:25)
    at UserController.addUser (/Users/ashamnx/Code/level2/build/Controllers/UserController.js:54:37)
    at Layer.handle [as handle_request] (/Users/ashamnx/Code/level2/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/ashamnx/Code/level2/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/ashamnx/Code/level2/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/ashamnx/Code/level2/node_modules/express/lib/router/layer.js:95:5)
    at /Users/ashamnx/Code/level2/node_modules/express/lib/router/index.js:281:22`

I was able to bypass it by updating `SchemaValidator.ts` file (in a fork). By replacing
`if(data.constructor.name !== field.type)`
with 
`if(data && data.constructor.name !== field.type)`

but Im not sure if this will have any side effects.

**Comment by azarus** [comment]
Hey, thanks for the feedback really appriciate it. I ran into this as well lately, i probably forgot to push my latest code that fixes this :)

**Comment by ashamnx** [comment]
It seems its happening when default value of `null` is set like
`@Property({ hidden: true })
	protected hashedPassword: string = null;`

when i removed the null it seems to work.
hope to see a fix soon.

**Comment by azarus** [comment]
Hmmm in that case it should only throw an error if the field is required. I'll be on it fixing it later tonight.

**Comment by azarus** [comment]
thank you, it's been fixed in the latest update.
